# Generated by Django 4.1.2 on 2022-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0004_alter_componentgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('management_key', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_subscriptions', models.BooleanField(default=True)),
                ('component_subscriptions', models.ManyToManyField(blank=True, related_name='subscribers', to='components.component')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
