# Generated by Django 4.1.2 on 2022-11-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_maintenance_end_automatically_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceupdate',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='maintenances.maintenance'),
        ),
    ]
