# Generated by Django 4.2.1 on 2023-06-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenances", "0007_maintenancetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetemplate",
            name="end_automatically",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="maintenancetemplate",
            name="start_automatically",
            field=models.BooleanField(default=True),
        ),
    ]
