# Generated by Django 4.1.2 on 2022-10-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
