# Generated by Django 4.1.2 on 2022-10-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='impact',
            field=models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=255),
        ),
    ]
