# Generated by Django 4.1.2 on 2022-10-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_options'),
        ('incidents', '0004_alter_incident_impact_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='components',
            field=models.ManyToManyField(related_name='incidents', to='components.component'),
        ),
    ]
