# Generated by Django 4.1.2 on 2022-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_incidentupdate_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='text',
            field=models.CharField(max_length=65536),
        ),
    ]
