# Generated by Django 4.1.7 on 2023-03-10 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_alter_incident_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
