# Generated by Django 4.2.1 on 2023-06-07 12:16

from django.db import migrations, models
import extras.utils


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0002_configrevision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("type_create", models.BooleanField(default=False)),
                ("type_update", models.BooleanField(default=False)),
                ("type_delete", models.BooleanField(default=False)),
                ("payload_url", models.CharField(max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("http_method", models.CharField(default="POST", max_length=30)),
                (
                    "http_content_type",
                    models.CharField(default="application/json", max_length=100),
                ),
                ("additional_headers", models.TextField(blank=True)),
                ("body_template", models.TextField(blank=True)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("conditions", models.JSONField(blank=True, null=True)),
                ("ssl_verification", models.BooleanField(default=True)),
                (
                    "ca_file_path",
                    models.CharField(blank=True, max_length=4096, null=True),
                ),
                (
                    "content_types",
                    models.ManyToManyField(
                        limit_choices_to=extras.utils.FeatureQuery("webhooks"),
                        related_name="webhooks",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.UniqueConstraint(
                fields=("payload_url", "type_create", "type_update", "type_delete"),
                name="extras_webhook_unique_payload_url_types",
            ),
        ),
    ]
