# Generated by Django 4.2.1 on 2023-12-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscribers", "0003_subscriber_incident_notifications_subscribed_only"),
        ("extras", "0004_webhook_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="subscriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="subscribers.subscriber",
            ),
        ),
    ]
