# Generated by Django 4.1.2 on 2022-11-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0004_alter_componentgroup_options'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeRobotMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('monitor_id', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(max_length=255)),
                ('status_id', models.IntegerField()),
                ('paused', models.BooleanField(default=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.component')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.metric')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
