# Generated by Django 4.1.2 on 2022-11-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_uptimerobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimerobotmonitor',
            name='monitor_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
