# Generated by Django 4.1.2 on 2022-11-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_uptimerobot', '0002_alter_uptimerobotmonitor_monitor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uptimerobotmonitor',
            options={'ordering': ['pk']},
        ),
    ]
