<?php
/*
 * Copyright (c) 2021 by HerrTxbias.
 *
 * Using / Editing this without my consent is not allowed.
 */

/*
 *  |---------------------------------------------------------
 *  |
 *  | PLEASE DO NOT EDIT THIS FILE
 *  |
 *  |---------------------------------------------------------
 */

return [
    'use_configcat' => boolval(env('STATUSPAGE_USE_CONFIGCAT', true)),
    'disable_ratelimiter' => env('STATUSPAGE_DISABLE_RATELIMITER', false),
];
