# Generated by Django 4.1.2 on 2022-10-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visibility', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('collapse', models.CharField(choices=[('expand_issue', 'Expand on Issue'), ('expand_always', 'Always Expanded')], default='expand_issue', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visibility', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('operational', 'Operational'), ('degraded_performance', 'Degraded Performance'), ('partial_outage', 'Partial Outage'), ('major_outage', 'Major Outage'), ('maintenance', 'Maintenance')], default='operational', max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('component_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.componentgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
