# Generated by Django 4.1.2 on 2022-10-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['component_group', 'order', 'name']},
        ),
    ]
