# Generated by Django 4.1.2 on 2022-10-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['component_group', 'order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='componentgroup',
            options={'ordering': ['pk']},
        ),
    ]
