# Generated by Django 4.1.2 on 2022-10-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_component_options_alter_componentgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentgroup',
            options={'ordering': ['order', 'pk']},
        ),
    ]
