# Generated by Django 4.1.4 on 2023-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_componentgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='show_historic_incidents',
            field=models.BooleanField(default=True),
        ),
    ]
