# Generated by Django 4.1.2 on 2022-11-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0004_alter_componentgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStatusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('create_incidents', models.BooleanField(default=False)),
                ('create_maintenances', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ExternalStatusComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('page_object_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.component')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_external_status_providers.externalstatuspage')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
