# Generated by Django 4.1.2 on 2022-11-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_external_status_providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalstatuscomponent',
            old_name='page',
            new_name='external_page',
        ),
    ]
