# Generated by Django 4.1.2 on 2022-11-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp_external_status_providers', '0002_rename_page_externalstatuscomponent_external_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalstatuscomponent',
            name='external_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sp_external_status_providers.externalstatuspage'),
        ),
    ]
